@TM:1403520743
@N:  :"":0:0:0:-1|Running in 32-bit mode
@N: CG364 :"d:\Microsemi\Libero_v9.1\Synopsys\synplify_E201009A-1\lib\proasic\proasic3.v":1168:7:1168:11|Synthesizing module INBUF
@N: CG364 :"d:\Microsemi\Libero_v9.1\Synopsys\synplify_E201009A-1\lib\proasic\proasic3.v":1959:7:1959:12|Synthesizing module CLKINT
@N: CG364 :"E:\GitHub\simdb-fpga\hdl\freq.v":25:7:25:10|Synthesizing module freq
@W: CL246 :"E:\GitHub\simdb-fpga\hdl\freq.v":29:22:29:26|M
@W: CL265 :"E:\GitHub\simdb-fpga\hdl\freq.v":72:3:72:8|M
@N: CG364 :"E:\GitHub\simdb-fpga\hdl\freq_dop.v":18:7:18:14|Synthesizing module freq_dop
@W: CL159 :"E:\GitHub\simdb-fpga\hdl\freq_dop.v":23:22:23:27|M
@W: CL265 :"E:\GitHub\simdb-fpga\hdl\freq_dop.v":40:0:40:5|M
@N: CG179 :"E:\GitHub\simdb-fpga\hdl\freq_dop.v":86:35:86:39|M
@N: CG364 :"E:\GitHub\simdb-fpga\hdl\led.v":21:7:21:9|Synthesizing module led
@W: CL190 :"E:\GitHub\simdb-fpga\hdl\led.v":33:4:33:9|M
@W: CL260 :"E:\GitHub\simdb-fpga\hdl\led.v":33:4:33:9|M
@N: CG364 :"E:\GitHub\simdb-fpga\hdl\sim_db_fpga.v":42:7:42:12|Synthesizing module sim_db
@W: CL159 :"E:\GitHub\simdb-fpga\hdl\sim_db_fpga.v":51:20:51:25|M
@W: CL169 :"E:\GitHub\simdb-fpga\hdl\sim_db_fpga.v":368:0:368:5|M
